### ISSUE TITLE
训练模型可以，预测的时候有问题

### ISSUE THREAD

**Issue by LBJ-Software** [yangapku/NN_SRLer#1]
Traceback (most recent call last):
  File "/home/ylq/公共的/pycharm-2017.3.2/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ylq/公共的/pycharm-2017.3.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ylq/PycharmProjects/Origina-NN_SRLer/src/nnsrler.py", line 42, in <module>
    preds = model.test(raw_test_data, test_feats)
  File "/home/ylq/PycharmProjects/Origina-NN_SRLer/src/model.py", line 283, in test
    trans_param = pickle.load(fin)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 3: ordinal not in range(128)

**Comment by LBJ-Software** [comment]
系统环境：tensorflow 1.4.1 ；  python 3.5.2

**Comment by yangapku** [comment]
您好，请问repo中已有的模型可以正常读取预测吗？

**Comment by LBJ-Software** [comment]
原有的模型和我试跑的模型用于预测都出现上面那个bug。use_crf设为False后可以预测，预测结果是：recall: 0.5458498023715415  precision: 0.10928226636068687  F: 0.1821058877826861，用您提供的预测文件预测结果是recall: 0.607509881422925  precision: 0.7192325690219934  F: 0.6586672380544247。

**Comment by yangapku** [comment]
不好意思一致未能回复。您好，我的TF环境和您的是一样的，但是我是python 2.7环境下跑的，问题似乎在pickle上，py2和py3不太兼容

**Comment by hrdxwandg** [comment]
我也遇到了这个问题，参考：
http://blog.csdn.net/lanchunhui/article/details/50034921

trans_param = pickle.load(fin) 改为：
trans_param = pickle.load(fin,encoding='latin1')
